CREATE TABLE HH_DEMOGRAPHIC (
    household_key INT PRIMARY KEY,
    AGE_DESC VARCHAR(10),
    MARITAL_STATUS_CODE VARCHAR(2),
    INCOME_DESC VARCHAR(10),
    HOMEOWNER_DESC VARCHAR(15),
    HH_COMP_DESC VARCHAR(20),
    HOUSEHOLD_SIZE_DESC VARCHAR(15),
    KID_CATEGORY_DESC VARCHAR(20));


CREATE TABLE CAMPAIGN_DESC (
    CAMPAIGN INT,
	DESCRIPTION VARCHAR(10),
    START_DAY INT,
    END_DAY INT,
    PRIMARY KEY (CAMPAIGN));


CREATE TABLE campaign_TABLE (
	household_key INT,
    CAMPAIGN INT,
    DESCRIPTION VARCHAR(10),
    FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC(CAMPAIGN),
    FOREIGN KEY (household_key) REFERENCES HH_DEMOGRAPHIC(household_key));


CREATE TABLE product (
    PRODUCT_ID INT PRIMARY KEY,
	COMMODITY_DESC VARCHAR(30),
    SUB_COMMODITY_DESC VARCHAR(30),
    MANUFACTURER INT,
    DEPARTMENT VARCHAR(20),
    BRAND VARCHAR(20),
    CURR_SIZE_OF_PRODUCT VARCHAR(20));


CREATE TABLE coupon (
	CAMPAIGN INT,
    COUPON_UPC BIGINT PRIMARY KEY,
    PRODUCT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES product(PRODUCT_ID),
    FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC(CAMPAIGN));
	


CREATE TABLE COUPON_REDEMPT (
    household_key INT,
    DAY INT,
    COUPON_UPC BIGINT,
    CAMPAIGN INT,
    FOREIGN KEY (household_key) REFERENCES HH_DEMOGRAPHIC(household_key),
    FOREIGN KEY (COUPON_UPC) REFERENCES coupon(COUPON_UPC),
    FOREIGN KEY (CAMPAIGN) REFERENCES campaign_desc(CAMPAIGN));

	
CREATE TABLE casual_data (
    PRODUCT_ID INT,
    STORE_ID INT,
    WEEK_NO INT,
    display INT,
    mailer CHAR(1),
    FOREIGN KEY (PRODUCT_ID) REFERENCES product(PRODUCT_ID));

	

CREATE TABLE transactions (
    household_key INT,
    BASKET_ID BIGINT,
    DAY INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    SALES_VALUE NUMERIC(10,2),
    STORE_ID INT,
	COUPON_MATCH_DISC NUMERIC(10,2),
	COUPON_DISC NUMERIC(10,2),
    RETAIL_DISC NUMERIC(10,2),
    TRANS_TIME INT,
    WEEK_NO INT,
    FOREIGN KEY (household_key) REFERENCES HH_DEMOGRAPHIC(household_key),
    FOREIGN KEY (PRODUCT_ID) REFERENCES product(PRODUCT_ID));

	
	
	
	
	
	
	

